config/routes.rb
Rails.application.routes.draw do

    root to: "pages#index"

    resources :students, only: [:index, :show] do
        resources :downloads, only: [:show]
    end

    resources :pages, only: [:index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord

end

app/models/student_pdf.rb
require "render_anywhere"

class StudentPdf
  include RenderAnywhere

  def initialize(student)
    @student = student
    @qr = RQRCode::QRCode.new( student.number, :size => 1, :level => :h )
  end

  def to_pdf
    kit = PDFKit.new(as_html, page_size: 'A4')
    kit.to_file("public/student.pdf")
  end

  def filename
    "Student #{student.id}.pdf"
  end

  private

    attr_reader :student
    attr_reader :qr

    def as_html
      render template: "students/pdf", layout: "student_pdf", locals: { student: student, qr: qr }
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController

    def show
      respond_to do |format|
        format.pdf { send_student_pdf }
      end
    end

    private

    def student_pdf
      student = Student.find(params[:id])
      StudentPdf.new(student)
    end

    def send_student_pdf
      send_file student_pdf.to_pdf,
        filename: student_pdf.filename,
        type: "application/pdf",
        disposition: "inline"
    end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def index
        @students = Student.all
    end
    
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

    def index
        @students = Student.all
    end

    def show
        @student = Student.find(params[:id])
    end

    def downloadPdf
        # kit = PDFKit.new('http://google.com')
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<div class="container">
  <nav class="navbar navbar-dark bg-inverse">
    <ul class="nav navbar-nav clearfix">
      <li class="nav-item">
        <button class="navbar-toggler hidden-sm-up nav-link" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2" aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label="Toggle navigation">
          &#9776;
        </button>
      </li>
    </ul>
    <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
      <%= link_to "Rails bootstrap", root_path, class: 'navbar-brand' %>
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Sj Coding Test" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Sj Coding Test" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Do+Hyeon" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="container-fluid">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </div>

    <footer>
      <div class="coder">&lt;/&gt; with <span>&hearts;</span> by Nazmi</div>
    </footer>
  </body>
</html>

app/views/layouts/student_pdf.erb
<!DOCTYPE html>
<html>
<head>
  <title>Student Profile</title>
  <style>
    <%= Rails.application.assets.find_asset('application.scss').to_s %>
  </style>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/pages/index.html.erb
<%= react_component('App', { students: @students }) %>

app/views/students/index.html.erb
<div class="students-heading">Robo Students</div>

<div class="list">

<% if @students.empty? %>

    <div class="coder justify-content-center">
        <h4>Please run <code>rails db:seed</code> in your terminal!</h4>
    </div>

<% else %>

    <% @students.each_slice(4) do |four_students| %>

        <div class="row justify-content-center">

        <% four_students.each do |student| %>

            <%= link_to student_path(id: student.id) do %>

                <div class="card" style="width: 18rem;">

                    <img class="card-img-top" src="https://robohash.org/<%= student.name %>">

                    <div class="card-body text-center">
                        <h5 class="card-title"><%= student.name %></h5>
                    </div>

                </div>

            <% end %>

        <% end %>
        </div>

    <% end %>
<% end %>
</div>

app/views/students/pdf.html.erb
<table class="profile-table">

    <thead>
        <th>Robo Student Profile</th>
    </thead>

    <tbody>

        <tr>
            <td><img class="img-fluid" src="https://robohash.org/<%= student.id %>"></td>
        </tr>

        <tr>
            <th class="label">Student Name</th>
        </tr>
        <tr>
            <td><%= student.name %></td>
        </tr>

        <tr>
            <th class="label">Faculty</th>
        </tr>
        <tr>
            <td><%= student.faculty %></td>
        </tr>

        <tr>
            <th class="label">Student Number</th>
        </tr>
        <tr>
            <td><%= student.number %></td>
        </tr>

    </tbody>

</table>

<center>
    <%= raw qr.as_html %>
</center>

app/views/students/show.html.erb
<div class="students-heading">Robo Student Profile</div>

<div class="row justify-content-center student-profile">

    <div class="card">

        <img class="card-img-top" src="https://robohash.org/<%= @student.id %>">
        <h4 class="mt-2"><strong><%= @student.name %></strong></h4>

        <p class="title">
            <small>Faculty:</small><br>
            <strong><%= @student.faculty %></strong>
        </p>

        <p>
            <small>Student Number:</small><br>
            <strong><%= @student.number %></strong>
        </p>

        <p>
            <%= link_to "Download Student Profile (PDF)",
                student_download_path(@student, @student, format: "pdf"),
                target: "_blank",
                class: "btn btn-primary"
            %>
        </p>

    </div>
</div>

<div class="row justify-content-center mt-4">
    <%= link_to 'Back to List', root_path, class: "btn btn-info" %>
</div>